language: node_js
node_js:
- '6'
deploy:
  provider: gae
  keyfile: app_engine-service_account_key.json
  project: atid-broadcast-app
  on: master
before_script:
- npm run compile
- npm run compile-server
cache:
  directories:
  - node_modules
before_deploy:
- openssl aes-256-cbc -K $encrypted_1a71114b70e1_key -iv $encrypted_1a71114b70e1_iv
  -in app_engine-service_account_key.json.enc -out app_engine-service_account_key.json
  -d
